import React from 'react';

const Skills = () => {
  return (
    <div className="main-container flex flex-col items-center justify-center mt-4 select-text mb-8">
      <div className="title-container w-full max-w-2xl bg-white p-4 shadow-lg rounded-t-lg">
        <h2 className="text-2xl font-bold text-center text-black md:text-left ">My Skills</h2>
      </div>
      <div className="content-container w-full max-w-2xl bg-gray-400 p-4 shadow-lg rounded-b-lg">
        <p className="text-base md:text-lg text-gray-700 ">
          <b>Comming Soon... Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium quidem, eum rerum consequuntur libero nemo, animi veritatis molestiae repudiandae ratione quisquam? Eaque necessitatibus dicta vel ratione quidem sed iste dolor!
          Officiis dicta autem obcaecati delectus itaque animi reprehenderit similique facere tempore tempora provident alias, hic beatae voluptates veritatis eos. Cupiditate illum voluptates eveniet sunt consequatur voluptatem earum, porro illo laudantium.
          Quibusdam, voluptatum laborum maiores quas, sint voluptate unde sunt beatae eum repellat doloribus, nihil nam hic aliquam asperiores dolores ea molestiae inventore. Dolorum tempora fugiat alias veritatis maxime perferendis aspernatur.
          A iure sequi fugit placeat animi ratione officia, facilis cum, culpa porro dolorum. Consequatur reiciendis fugiat nam necessitatibus debitis, adipisci numquam beatae ipsa quam ea dolorem, impedit quo magni ullam!
          Eaque modi magni, eligendi odit ipsam dolorem commodi, quasi unde nemo in corrupti, nesciunt praesentium delectus velit voluptas! Distinctio nobis a dignissimos dicta repellat cupiditate commodi labore sapiente nostrum! Animi.
          Aliquid sit nam omnis reprehenderit ut veniam ad laborum corrupti commodi ullam magni expedita laboriosam cupiditate magnam doloribus libero distinctio nulla dignissimos, quasi, repellendus minus neque sapiente temporibus. Autem, illo.
          Deserunt corrupti harum, qui voluptatibus ducimus voluptatem labore explicabo laborum id laboriosam dicta facere debitis esse optio magnam odio aspernatur unde cumque praesentium voluptas quod nostrum modi molestiae! Tempora, at.
          Voluptate excepturi est, velit beatae inventore dolores necessitatibus facere corrupti architecto molestiae magnam minus numquam! Velit, laudantium repudiandae obcaecati quia assumenda quae totam commodi. Eum autem aperiam consectetur voluptate alias!
          Assumenda atque debitis id, quo accusantium iste veritatis necessitatibus dolorem dolor aliquid laudantium cum deserunt vitae in esse nobis velit fuga facilis sit eligendi veniam! Laudantium autem eveniet officia adipisci.
          Eveniet eum consequatur at. Quia voluptatibus animi consequuntur id, fugit non quod impedit, laudantium ipsam inventore reprehenderit temporibus atque enim, soluta voluptates error molestias? Perspiciatis dolorum molestiae animi esse magni?
          Vel fugit, placeat omnis praesentium distinctio nihil vero consequuntur molestias voluptate dolores quam. Non voluptas quam fugiat natus repudiandae, iusto sapiente quaerat dolore quae ipsam ea accusantium maiores! Iste, voluptatem.
          Accusamus libero iusto, enim quia veritatis consequuntur error! Dignissimos obcaecati qui mollitia rerum incidunt cum nesciunt ut nisi debitis? Repudiandae repellendus impedit ut alias assumenda, quos iusto necessitatibus cumque magni.
          Nulla obcaecati vitae temporibus aspernatur vero molestias corrupti doloribus iusto fugit, eos aliquam excepturi? Quod assumenda eos iusto? Obcaecati dolor, quia cumque pariatur quisquam est laboriosam doloribus optio odio quis!
          Repellendus illo illum quis perferendis, nihil eum molestiae exercitationem sed, libero possimus facere necessitatibus rem dolorum id quod, accusantium voluptate iste ut. Minus enim autem impedit? Vero accusamus eligendi commodi.
          Iste totam a vitae, minima voluptatum asperiores quos provident excepturi velit nobis commodi enim, voluptates sit officiis inventore distinctio quibusdam illo repudiandae quam! Cumque, qui sapiente architecto quae porro provident?
          Eos, recusandae repellat illum reprehenderit beatae temporibus ipsum, consequuntur voluptates optio ipsa molestias dolorum corporis doloribus voluptas voluptatum quasi quo cum ex nesciunt qui. Sunt pariatur earum illo reprehenderit cumque!
          Nobis, minus doloremque! Reprehenderit perferendis cupiditate facere aspernatur magnam recusandae architecto corrupti hic vitae ea nesciunt repudiandae rem odio doloribus, doloremque iure quaerat dolorum quasi laudantium molestias, eveniet ut necessitatibus!
          Sequi ratione maiores dolor quod accusamus dolores asperiores suscipit vel, corrupti accusantium error, facere officia, nam delectus doloremque! Quod, obcaecati id suscipit ipsam cumque accusamus hic eveniet voluptatum dolore harum.
          Veniam magnam officia ipsam minus quos iste consequuntur doloribus ratione fugiat placeat expedita porro corrupti, voluptate facere id rem ab labore laudantium ut atque. Saepe recusandae repudiandae vel ullam impedit?
          Corrupti itaque sunt facere inventore aspernatur esse praesentium possimus quia doloribus, qui repellat impedit nobis saepe nostrum soluta harum placeat quo doloremque illum distinctio deleniti dicta voluptas exercitationem! Non, facilis.
          Laboriosam voluptatum praesentium nam hic optio quibusdam soluta veritatis odit inventore omnis! Similique repudiandae quam autem. Non beatae, dolorem ratione delectus vel placeat rerum impedit, exercitationem rem dolorum ipsam sapiente!
          Sunt sequi quis, placeat totam aliquam voluptatum voluptatem. Explicabo porro quia, ad vel quaerat nam quod ratione commodi harum dicta ab ipsa debitis sed ducimus voluptas quo delectus repudiandae saepe.
          Inventore aliquam quae dolorem consectetur minima mollitia hic, repellat unde quos illo quod earum. Animi voluptas, aliquid minus nihil provident dicta, laborum inventore delectus magnam dolore molestiae. Corrupti, sunt ab.
          Fuga commodi, assumenda asperiores, excepturi eum nam, corrupti vitae dignissimos molestias sed cumque quas hic at expedita quo quia vero laudantium voluptas illo porro quam aut esse! Debitis, veritatis deleniti.
          Error aliquam sequi delectus doloremque omnis laborum dolor tempora voluptates pariatur consectetur blanditiis quisquam, aspernatur dolorum quasi aperiam! Totam, harum dolore. Minus officia possimus aliquid? Maiores deleniti iure obcaecati ipsum.
          Esse culpa modi vel, numquam odit beatae corrupti quas repellat distinctio maiores quam, dolor omnis ratione facere suscipit rerum! Eius repellendus, laboriosam blanditiis necessitatibus veniam veritatis nesciunt. Nemo, facilis rerum?
          Cumque iusto optio beatae hic, nam culpa temporibus iste asperiores iure minus tenetur expedita soluta dolorum? Reiciendis at, maxime veniam amet cupiditate rem pariatur vitae, obcaecati repellat aperiam odit enim?
          Laborum deserunt mollitia non aliquam natus ad, ipsam, tempora placeat, inventore sunt nulla nam perspiciatis optio tempore vitae recusandae reprehenderit. Accusamus, recusandae quis. Eaque, eius perferendis. Veniam ratione ipsam non.
          Nostrum soluta deleniti rerum rem culpa fugiat reiciendis amet laudantium ea illum. Facilis provident odit id impedit, vero molestias aliquid debitis soluta unde tenetur. Eveniet hic repellat sapiente impedit praesentium.
          Amet totam velit enim ea non, iste voluptate aspernatur adipisci? Dolorem facere suscipit, numquam ea repudiandae, officia recusandae vitae, enim illo quaerat consequuntur cupiditate dolores ratione architecto labore ab molestias?
          Hic doloribus inventore laborum facere! Nihil delectus tenetur molestiae culpa illo et error nobis vero distinctio? Ullam, placeat pariatur. Illo fuga neque ad quibusdam ipsa. Excepturi consequuntur culpa hic veritatis.
          Rerum, deleniti ducimus vel magni, nisi id possimus illo corrupti culpa quas esse exercitationem. Alias quod vitae atque tempore, fugit saepe dignissimos ipsum animi nihil sunt, dolorum quisquam veritatis eveniet!
          Animi reprehenderit repudiandae necessitatibus et accusamus, libero porro ullam! Sed hic, facilis voluptatibus nemo, explicabo, incidunt impedit repudiandae sapiente neque aperiam quidem vero quaerat harum aliquam qui magnam labore ipsum!
          A quia voluptates eaque voluptatum dolorum omnis voluptatem quam recusandae. Sit nisi non iure deserunt eligendi omnis odio vel consectetur doloremque voluptates libero, provident minima, quas incidunt ullam voluptatibus iste.
          Veniam eius sequi assumenda totam, ex qui, dolores aliquid nostrum quae libero perferendis quod aspernatur culpa delectus itaque velit harum perspiciatis quaerat, voluptatibus quidem labore. Nostrum incidunt eveniet minima? Nesciunt.
          Impedit, facere! Velit quas labore a dolorum neque ad odio. Autem cumque illum voluptatum quis fugit. Veritatis doloremque explicabo, repellendus vitae labore fuga aspernatur asperiores! Eum sit cupiditate est reiciendis.
          Optio sunt perspiciatis tempora distinctio mollitia? At beatae porro voluptas vitae minima, delectus omnis nobis laboriosam doloribus, animi incidunt modi consequatur ab, sit veniam ad aspernatur rerum corrupti. Ut, eius?
          Praesentium, enim, magni atque laborum laboriosam dicta soluta neque repudiandae molestiae nemo sed, eveniet qui expedita maxime quod molestias modi odio amet recusandae iure quasi quis distinctio! Dignissimos, atque suscipit!
          Rem minus inventore quibusdam suscipit blanditiis quod? Rem quos veniam libero numquam placeat magni ipsa officiis, molestias distinctio molestiae recusandae facilis alias commodi possimus quidem, porro doloribus accusantium ullam ipsam?
          Consectetur eligendi quibusdam quae tempore ipsa delectus ad dignissimos. Modi, ad voluptatem, accusantium adipisci cumque maxime delectus expedita consequatur impedit cum perferendis quod libero eaque sapiente, tempore neque laborum ratione.
          Magnam eaque eligendi quisquam nemo officiis facilis suscipit numquam consequatur ab possimus perspiciatis ut, deserunt harum ad odio recusandae temporibus alias voluptatum quis quos repellat pariatur assumenda minus. Unde, suscipit.
          Incidunt itaque veritatis sint modi, quaerat architecto velit suscipit dolore ab quo soluta non sequi similique illo esse? Rerum amet tenetur sunt animi dolore totam eveniet dolores cum quod omnis!
          Aperiam fugit hic excepturi? Reprehenderit nostrum deleniti voluptates quis? Officia accusantium quasi numquam quod obcaecati, hic facilis beatae aliquid rem laborum! Ipsa beatae laborum incidunt aperiam nihil pariatur rerum laboriosam.
          Alias nisi voluptates, voluptas ipsam nemo quos officia facere eum earum dolorum excepturi facilis? Soluta tenetur quae neque est! Repudiandae eligendi vero ipsa, vitae harum sed eius iste aliquid incidunt!
          Molestias et fugiat omnis porro libero exercitationem. Quam iusto sit neque harum animi quas, maxime officiis culpa deserunt ipsam. Laboriosam dolorem ullam blanditiis commodi dignissimos sed! Molestias reiciendis animi ut.
          Eos corrupti, nemo natus blanditiis temporibus exercitationem, animi dolorum aperiam error vitae eius laboriosam porro. Natus ut dignissimos corporis, sint, sapiente exercitationem ad praesentium fugit quas sequi ducimus? Deleniti, iure.
          Earum pariatur quibusdam eaque accusamus ea! Quam, molestias ipsa. Ea assumenda iure aliquam accusamus. Aliquid, ab? Earum non cumque illum, eum inventore possimus debitis, error laboriosam quibusdam, officia repudiandae minima.
          Atque consectetur cum eveniet minima cupiditate quasi. Nulla corrupti at, quibusdam, ratione impedit sequi praesentium neque, facere dolorum illo quis officiis recusandae quisquam perferendis? Placeat non consequatur quaerat tempora qui.
          Eaque maiores beatae saepe ipsam optio doloremque ipsum assumenda eum sint. Quam dolorem expedita blanditiis asperiores saepe mollitia consectetur libero, ratione excepturi eaque culpa incidunt. Molestiae nobis libero maiores nihil!
          Aut rem maxime commodi adipisci tempora laboriosam placeat pariatur assumenda fugit veritatis eius voluptatibus laborum, totam suscipit nobis? Repellat itaque debitis quam ducimus fugit aliquid rem aspernatur consequuntur. Adipisci, obcaecati.
          Similique in omnis odit velit molestiae soluta culpa laboriosam? Est nesciunt, ab quod illum voluptates cumque quasi blanditiis? Tempore nostrum magni placeat. In voluptate libero eveniet voluptates minima, deserunt illum.
          Adipisci illum consectetur vero sapiente rerum corporis ea sunt, facere iste quos iure. Aut pariatur soluta ut esse fugiat, a quasi voluptatem sunt. Voluptas facilis nulla ipsam reiciendis perspiciatis consectetur?
          Sed quae necessitatibus deserunt tempore dolore voluptatibus porro vel, in labore enim fugit optio magnam sequi sunt. Sint excepturi, iusto dolores blanditiis libero dicta iste necessitatibus totam amet assumenda consectetur!
          Cum est officia tempore ut laboriosam harum. Incidunt, ipsam nobis. Quo inventore amet minus non? Ex id, praesentium voluptates architecto nesciunt fugit incidunt fugiat, ratione exercitationem voluptatum nisi vitae adipisci?
          Veritatis pariatur mollitia, libero vitae ab earum molestiae perspiciatis, error voluptatibus eveniet doloribus cum dolores maiores qui nostrum aliquam ipsum nisi eum commodi itaque illo maxime vel nihil iste! Consectetur!
          Nesciunt dolores esse vel numquam incidunt, fugit rem ex, velit necessitatibus porro nulla sunt dolor dolorem eum quas laborum ad ipsum aut facilis excepturi. Fugiat, non aut! Illum, impedit non?
          Possimus labore voluptas expedita laborum, quas ipsum deleniti eveniet hic odio natus ipsa magnam repellendus voluptatem optio quos quasi rem nemo! Nesciunt saepe necessitatibus dignissimos est veritatis? Qui, sed harum.
          Tempora in perferendis sapiente vitae placeat ratione repellat enim fuga labore quidem, inventore soluta quibusdam vero praesentium expedita. Ducimus quam totam cumque minima vel voluptates quia minus quis ipsum odio!
          Quod iure aperiam nemo laboriosam possimus, id maxime repellat nulla nihil perspiciatis itaque enim nesciunt tempore qui facilis. Eaque, odit. At voluptatum aspernatur ipsa veniam! Porro recusandae error possimus ipsam.
          Adipisci, nam nisi! Reprehenderit placeat fuga veritatis eaque vitae obcaecati esse vero debitis porro recusandae rem, doloribus quo odio voluptates ab adipisci ullam, ducimus, harum illo tempora expedita temporibus. Consequatur!
          Veniam soluta voluptas laborum temporibus corrupti! Vero nobis placeat voluptatem odio perspiciatis, voluptates recusandae enim veniam quidem quam perferendis quasi suscipit obcaecati, neque sunt reprehenderit nam et porro praesentium ad.
          Natus libero, recusandae, rerum exercitationem modi provident possimus totam reprehenderit facilis neque, cupiditate esse sequi at eaque porro maxime vitae reiciendis optio voluptatibus quis laboriosam nihil ullam? Temporibus, deleniti hic.
          Illum, nesciunt mollitia maiores id laudantium sapiente praesentium molestias amet sint, in necessitatibus obcaecati debitis, doloribus atque perspiciatis. Repudiandae ratione ducimus sit voluptas sequi temporibus sunt quam nostrum maxime doloribus.
          Inventore voluptatibus vitae et. Reiciendis vero consequatur minima officia eum, ab harum sit aspernatur explicabo fugit magni corporis aliquid unde vitae! Nesciunt voluptatibus deleniti illo molestiae nihil quidem accusantium? Praesentium!
          Quia quis consequatur animi inventore ipsam enim quo corrupti sapiente tempora! Porro optio quae, esse saepe praesentium rem voluptatum nobis, adipisci fugiat tenetur, incidunt ipsa in. Fugit consequuntur beatae odit.
          Cum asperiores eos mollitia facilis ut odit modi! Voluptates facilis iusto quidem debitis nihil neque rem a omnis? Earum esse modi vitae blanditiis consectetur quae, dolor ut! Cum, quis cupiditate!
          Dolorum placeat, id corporis dolore, alias ea dolorem unde, ipsum reprehenderit ut molestias consectetur minus. Nihil nisi eos assumenda molestiae et rem, officiis, nam, corporis exercitationem qui culpa minus? Quis.
          Id ex accusantium laborum deleniti similique. Beatae cupiditate consequuntur dolorem architecto assumenda similique ad rem aspernatur veniam sapiente? Perspiciatis hic illum labore possimus blanditiis voluptatibus eos quo nobis! Hic, eaque.
          Tenetur facilis, vero, nihil aut dolore esse perspiciatis temporibus, beatae eum illo sint? Consequuntur, dignissimos! Quidem excepturi non temporibus nostrum esse, adipisci fugiat totam quos architecto nihil voluptatum, tempore labore.
          Iste eveniet perspiciatis commodi vel accusantium dolorum beatae, delectus doloremque corrupti ipsam deleniti inventore, impedit nulla provident voluptatibus praesentium eum veritatis adipisci. Eos sapiente quisquam, quaerat architecto facere tempora commodi.
          Nobis magni rem suscipit harum voluptates tempore dolore inventore error, veniam ut ipsam libero voluptatem id beatae! Temporibus sunt modi tenetur esse totam velit pariatur atque saepe deleniti. Deleniti, delectus?
          Distinctio ullam, ea quod fuga, neque sit modi cumque facilis deserunt, quia dolore id ratione unde inventore blanditiis vel dolores consequatur ab consectetur. Blanditiis, sint animi necessitatibus asperiores laborum repudiandae?
          A odit vitae placeat! Omnis atque at ratione nesciunt dolor itaque ut provident quisquam mollitia repellat iusto, dicta voluptatibus, earum voluptas eaque assumenda fugit sint laborum perspiciatis maiores, dolorum suscipit!
          Dolore, eligendi similique ad optio pariatur ut deleniti facere quibusdam cupiditate suscipit aliquid in temporibus expedita maiores nulla et sequi asperiores! Error voluptates omnis libero impedit delectus illum consequuntur earum.
          Consectetur facilis debitis unde, repudiandae optio maxime vitae tempore nobis obcaecati! Pariatur, molestiae! Beatae nihil nostrum molestias, fugit, consectetur minima officia tempore quo distinctio suscipit asperiores aliquid esse sapiente. Soluta?
          Dolorem, minus! Eaque quaerat iste mollitia beatae magnam asperiores quod quas fuga dolores, tenetur optio placeat nesciunt voluptatum a consequatur, rem autem itaque tempore commodi temporibus esse. Officiis, nesciunt eveniet!
          Id, quibusdam amet. Cum ut repellat eius doloremque deleniti tempore iusto ipsam labore itaque. Provident temporibus omnis expedita, voluptatum quas maxime natus iure nam quaerat necessitatibus odit hic quia voluptatem?
          Mollitia deserunt quibusdam incidunt natus repudiandae optio, magnam officiis necessitatibus aliquam minima, non nobis eos voluptatum ducimus amet quam tenetur porro quis eveniet. Sequi, quod itaque consectetur aperiam autem provident!
          Expedita, molestiae quod culpa odit vel sint aperiam minima sequi? Repudiandae sit quaerat velit laboriosam exercitationem, vitae et vero debitis necessitatibus ducimus dolorem, repellat rem corporis magnam? Magnam, ea tempore.
          Laboriosam, assumenda repellendus. Eligendi dignissimos totam hic libero obcaecati aperiam est ratione, eos et facere inventore amet soluta dolores nemo suscipit distinctio eaque voluptate ad rem explicabo dolorum dolore optio!
          Quo consequatur maiores modi exercitationem natus? Deleniti voluptas animi itaque nihil quis dolorem! Odit facilis sapiente magnam asperiores voluptas non enim iste adipisci quo provident, laudantium commodi et totam laboriosam.
          Reiciendis iure porro atque modi eligendi aspernatur nobis voluptas perferendis illum. Et velit eos facere, veniam repellat ab corporis ut nisi nemo numquam molestias magnam dicta non perferendis dignissimos odio.
          Suscipit reiciendis odit consectetur maiores laborum quidem consequatur debitis minima, mollitia voluptates eligendi a itaque sed numquam voluptas ex cumque, voluptatum impedit quae non quos similique? Explicabo voluptatibus optio minus?
          Velit iusto maxime magni animi voluptatibus laboriosam nostrum, dicta error ea adipisci ipsa unde sunt necessitatibus maiores. Ad cumque quae, minus nostrum architecto fugiat alias optio reprehenderit autem exercitationem dolor.
          Ipsa nostrum molestiae praesentium vero beatae saepe aliquam velit sunt architecto unde tenetur possimus laudantium quidem illo debitis dignissimos enim veritatis consequatur, mollitia harum, voluptas in sed exercitationem corrupti! Ipsam.
          Possimus accusamus, facilis mollitia, autem sit magni fuga vero officiis, saepe porro atque perspiciatis? Rerum accusamus quaerat similique consectetur sit excepturi rem, praesentium non neque minus. Voluptatem est minus possimus.
          Aliquam a, quasi assumenda adipisci consequatur numquam distinctio sint magni esse. Dignissimos dicta ex quibusdam voluptatibus expedita beatae tenetur adipisci maiores. Reprehenderit eveniet recusandae saepe itaque iste hic eaque quibusdam!
          Esse, accusamus ex molestiae assumenda rerum cupiditate voluptate, error animi fugit aperiam delectus culpa consectetur quo possimus cumque corporis dolor enim cum, impedit ullam. Et eligendi illum eaque animi optio!
          Tempore laudantium eius aliquam, accusamus sunt similique perferendis quas architecto in temporibus quos sequi, aperiam aut odit ab consequuntur at. Beatae fugit ipsam ullam voluptate maiores dicta repellendus velit fuga?
          Maxime pariatur aut atque eveniet ipsam, culpa repudiandae officiis delectus! Inventore, praesentium officia nulla tempore, ex animi illum similique asperiores maiores reprehenderit, assumenda aspernatur dicta? Harum qui placeat incidunt adipisci.
          Rem odit maxime sunt minima quos dicta porro velit perferendis consequuntur dolore. Eveniet minima, ipsum soluta beatae ullam provident vero eius voluptas, distinctio mollitia hic odit quam dolor minus architecto?
          Sed asperiores voluptas quia ut esse assumenda in iusto, vitae odit ratione sit consequuntur, quae, est aliquid cum adipisci. Eligendi nostrum inventore quisquam repudiandae totam repellat maiores dolor libero ratione?
          Voluptatem, voluptatibus! Qui, explicabo reprehenderit sit aperiam laudantium nihil veritatis ex nulla ducimus sint ipsum, quasi accusamus eaque corrupti! Commodi accusantium eum a quaerat eaque doloribus culpa velit, cumque exercitationem.
          Eaque quaerat veritatis eveniet necessitatibus alias quidem, fugit, molestiae adipisci nobis magni reprehenderit vel tenetur cupiditate vero animi velit. Aspernatur molestiae omnis illo exercitationem accusamus dolorum possimus natus esse ea.
          Eos id voluptate esse? Illum nam dolor blanditiis quam cupiditate minima mollitia quaerat quod, fugiat, consequatur earum similique nemo, delectus assumenda aperiam illo eum atque iure rerum veritatis hic quos!
          Dolore quae qui soluta temporibus quas optio iste inventore dignissimos, nulla, odit provident omnis eaque numquam at, maxime beatae minus minima consequuntur. Eaque odio quasi delectus, hic omnis vel possimus.
          Sunt eos odit voluptates repudiandae, quod aperiam veritatis odio! Corporis est architecto iure nobis, a hic ratione delectus, aperiam maxime quae dolor veritatis voluptatum, explicabo error sit officiis. Voluptas, velit?
          Odio assumenda atque dolore quam, aliquid corporis quod delectus, sed ipsa illum tenetur. In fuga amet, fugiat praesentium iste quibusdam iusto similique ipsum cumque reiciendis atque ut aspernatur, repellendus sapiente.
          Nesciunt, alias fugiat porro veniam reprehenderit doloremque eveniet vel numquam dicta! Dolorem, laboriosam. Omnis ipsum, libero saepe quae architecto ipsam soluta harum quis sequi consectetur nihil cupiditate veritatis praesentium pariatur.
          Voluptas quasi repellat odit ullam sit dolores eveniet, error architecto recusandae iusto, ea deleniti, officiis autem perspiciatis labore totam dolorum quia quos similique nihil cupiditate maiores provident deserunt! Non, aut!</b>
        </p>
      </div>
    </div>
  );
};

export default Skills;